### ISSUE TITLE
Ошибка типизации при обратном связывании.

### ISSUE THREAD

**Issue by Fullchaos** [pozitronik/yii2-relations#17]
При сохранении связи linkModels, $backLink = true, unlinkModel падает в TypeError.

`app\models\users\active_record\relations\RelationUsersToPartners::unlinkModel(): Argument #2 ($slave) must be of type yii\db\ActiveRecord|string|int|null, array given, called in /var/www/vendor/pozitronik/yii2-relations/src/traits/RelationsTrait.php on line 246`

Данные
`unlinkModel(4, ['2', '4'], null)`

Пример таблицы 
<img width="425" alt="Снимок экрана 2023-01-17 в 16 49 26" src="https://user-images.githubusercontent.com/41751396/212905906-5d7e9fca-a115-4de0-9a4f-774c106de4ed.png">

**Comment by Fullchaos** [comment]
``

**Comment by pozitronik** [comment]
Проблема возникла из-за того, что в rules() модели релейшена атрибуты были описаны неожиданным способом: вторичный атрибут шёл первым, первичный - вторым. `$backLink` не влияет на это, он задаёт только логику связывания атрибутов.

Начиная с 1.1.1 введены атрибуты `$primaryAttributeName` и `$secondaryAttributeName`, позволяющие явно задать порядок ключей, а не пытаться вытащить их из правил валидатора.
